; Vibe Remote Buddy Windows installer (NSIS 3, MUI2).
; Per-user install into %LOCALAPPDATA%\Programs, HKCU registry only,
; so normal users never hit UAC. Input is a verified portable package;
; SRCDIR / OUTFILE / ICONFILE / version defines are generated by
; scripts/make-installer.mjs into build/installer/defines.nsh.

Unicode true
ManifestDPIAware true
RequestExecutionLevel user
AllowRootDirInstall false
SetCompressor /SOLID lzma

!include "MUI2.nsh"
!include "FileFunc.nsh"

!define APP_NAME "Vibe Remote Buddy"
!define APP_EXE "Vibe Remote Buddy.exe"
!define ARP_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_NAME}"

!include "..\build\installer\defines.nsh"

Name "${APP_NAME}"
OutFile "${OUTFILE}"
BrandingText "${APP_NAME} ${DISPLAY_VERSION}"

VIProductVersion "${VERSION4}"
VIAddVersionKey "ProductName" "${APP_NAME}"
VIAddVersionKey "ProductVersion" "${DISPLAY_VERSION}"
VIAddVersionKey "FileDescription" "${APP_NAME} Installer"
VIAddVersionKey "FileVersion" "${VERSION4}"
VIAddVersionKey "LegalCopyright" "${PUBLISHER}"

InstallDir "$LOCALAPPDATA\Programs\${APP_NAME}"
InstallDirRegKey HKCU "Software\${APP_NAME}" "InstallDir"

!define MUI_ICON "${ICONFILE}"
!define MUI_UNICON "${ICONFILE}"
!define MUI_ABORTWARNING
!define MUI_LANGDLL_REGISTRY_ROOT HKCU
!define MUI_LANGDLL_REGISTRY_KEY "Software\${APP_NAME}"
!define MUI_LANGDLL_REGISTRY_VALUENAME "Installer Language"
!define MUI_FINISHPAGE_RUN "$INSTDIR\${APP_EXE}"
!define MUI_FINISHPAGE_RUN_TEXT "$(RunApp)"

!insertmacro MUI_PAGE_LICENSE "${SRCDIR}\LICENSE"
!insertmacro MUI_PAGE_COMPONENTS
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES

; English first: it is also the fallback for silent installs.
!insertmacro MUI_LANGUAGE "English"
!insertmacro MUI_LANGUAGE "SimpChinese"
!insertmacro MUI_LANGUAGE "TradChinese"
!insertmacro MUI_LANGUAGE "Japanese"
!insertmacro MUI_LANGUAGE "Korean"
!insertmacro MUI_LANGUAGE "German"
!insertmacro MUI_LANGUAGE "French"
!insertmacro MUI_LANGUAGE "Spanish"
!insertmacro MUI_LANGUAGE "Italian"
!insertmacro MUI_LANGUAGE "Russian"
!insertmacro MUI_LANGUAGE "PortugueseBR"

LangString SecDesktop ${LANG_ENGLISH} "Desktop shortcut"
LangString DescCore ${LANG_ENGLISH} "The application and all bundled resources."
LangString DescDesktop ${LANG_ENGLISH} "Add a shortcut to the desktop."
LangString MsgCloseApp ${LANG_ENGLISH} "${APP_NAME} is still running. Close it and click Retry."
LangString RunApp ${LANG_ENGLISH} "Run ${APP_NAME}"

LangString SecDesktop ${LANG_SIMPCHINESE} "桌面快捷方式"
LangString DescCore ${LANG_SIMPCHINESE} "应用程序及全部附带资源。"
LangString DescDesktop ${LANG_SIMPCHINESE} "在桌面创建快捷方式。"
LangString MsgCloseApp ${LANG_SIMPCHINESE} "${APP_NAME} 仍在运行，请先关闭，再点击重试。"
LangString RunApp ${LANG_SIMPCHINESE} "运行 ${APP_NAME}"

LangString SecDesktop ${LANG_TRADCHINESE} "桌面捷徑"
LangString DescCore ${LANG_TRADCHINESE} "應用程式及全部附帶資源。"
LangString DescDesktop ${LANG_TRADCHINESE} "在桌面建立捷徑。"
LangString MsgCloseApp ${LANG_TRADCHINESE} "${APP_NAME} 仍在執行，請先關閉，再按重試。"
LangString RunApp ${LANG_TRADCHINESE} "執行 ${APP_NAME}"

LangString SecDesktop ${LANG_JAPANESE} "デスクトップショートカット"
LangString DescCore ${LANG_JAPANESE} "アプリケーションと同梱リソース。"
LangString DescDesktop ${LANG_JAPANESE} "デスクトップにショートカットを作成します。"
LangString MsgCloseApp ${LANG_JAPANESE} "${APP_NAME} が実行中です。終了してから再試行をクリックしてください。"
LangString RunApp ${LANG_JAPANESE} "${APP_NAME} を実行"

LangString SecDesktop ${LANG_KOREAN} "바탕 화면 바로 가기"
LangString DescCore ${LANG_KOREAN} "응용 프로그램 및 포함된 리소스."
LangString DescDesktop ${LANG_KOREAN} "바탕 화면에 바로 가기를 만듭니다."
LangString MsgCloseApp ${LANG_KOREAN} "${APP_NAME}이(가) 실행 중입니다. 종료한 후 다시 시도를 클릭하십시오."
LangString RunApp ${LANG_KOREAN} "${APP_NAME} 실행"

LangString SecDesktop ${LANG_GERMAN} "Desktop-Verknüpfung"
LangString DescCore ${LANG_GERMAN} "Anwendung und alle mitgelieferten Ressourcen."
LangString DescDesktop ${LANG_GERMAN} "Verknüpfung auf dem Desktop anlegen."
LangString MsgCloseApp ${LANG_GERMAN} "${APP_NAME} wird noch ausgeführt. Bitte beenden und auf Wiederholen klicken."
LangString RunApp ${LANG_GERMAN} "${APP_NAME} ausführen"

LangString SecDesktop ${LANG_FRENCH} "Raccourci bureau"
LangString DescCore ${LANG_FRENCH} "L'application et toutes les ressources incluses."
LangString DescDesktop ${LANG_FRENCH} "Créer un raccourci sur le bureau."
LangString MsgCloseApp ${LANG_FRENCH} "${APP_NAME} est encore en cours d'exécution. Fermez-le puis cliquez sur Réessayer."
LangString RunApp ${LANG_FRENCH} "Lancer ${APP_NAME}"

LangString SecDesktop ${LANG_SPANISH} "Acceso directo al escritorio"
LangString DescCore ${LANG_SPANISH} "La aplicación y todos los recursos incluidos."
LangString DescDesktop ${LANG_SPANISH} "Crear un acceso directo en el escritorio."
LangString MsgCloseApp ${LANG_SPANISH} "${APP_NAME} sigue en ejecución. Ciérrelo y haga clic en Reintentar."
LangString RunApp ${LANG_SPANISH} "Ejecutar ${APP_NAME}"

LangString SecDesktop ${LANG_ITALIAN} "Collegamento sul desktop"
LangString DescCore ${LANG_ITALIAN} "L'applicazione e tutte le risorse incluse."
LangString DescDesktop ${LANG_ITALIAN} "Crea un collegamento sul desktop."
LangString MsgCloseApp ${LANG_ITALIAN} "${APP_NAME} è ancora in esecuzione. Chiuderlo e fare clic su Riprova."
LangString RunApp ${LANG_ITALIAN} "Esegui ${APP_NAME}"

LangString SecDesktop ${LANG_RUSSIAN} "Ярлык на рабочем столе"
LangString DescCore ${LANG_RUSSIAN} "Приложение и все входящие в комплект ресурсы."
LangString DescDesktop ${LANG_RUSSIAN} "Создать ярлык на рабочем столе."
LangString MsgCloseApp ${LANG_RUSSIAN} "Приложение ${APP_NAME} ещё запущено. Закройте его и нажмите Повторить."
LangString RunApp ${LANG_RUSSIAN} "Запустить ${APP_NAME}"

LangString SecDesktop ${LANG_PORTUGUESEBR} "Atalho na área de trabalho"
LangString DescCore ${LANG_PORTUGUESEBR} "O aplicativo e todos os recursos incluídos."
LangString DescDesktop ${LANG_PORTUGUESEBR} "Cria um atalho na área de trabalho."
LangString MsgCloseApp ${LANG_PORTUGUESEBR} "O ${APP_NAME} ainda está em execução. Feche-o e clique em Repetir."
LangString RunApp ${LANG_PORTUGUESEBR} "Executar ${APP_NAME}"

Function .onInit
  SetRegView 64
  !insertmacro MUI_LANGDLL_DISPLAY
FunctionEnd

Function un.onInit
  SetRegView 64
  !insertmacro MUI_UNGETLANGUAGE
FunctionEnd

Section "${APP_NAME}" SEC_CORE
  SectionIn RO
  SetOutPath "$INSTDIR"
check_running:
  ClearErrors
  IfFileExists "$INSTDIR\${APP_EXE}" 0 copy_files
  Delete "$INSTDIR\${APP_EXE}"
  IfErrors 0 copy_files
  MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "$(MsgCloseApp)" IDRETRY check_running
  Abort
copy_files:
  File /r "${SRCDIR}\*"
  CreateDirectory "$SMPROGRAMS\${APP_NAME}"
  CreateShortCut "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}"
  WriteRegStr HKCU "Software\${APP_NAME}" "InstallDir" "$INSTDIR"
  WriteRegStr HKCU "${ARP_KEY}" "DisplayName" "${APP_NAME}"
  WriteRegStr HKCU "${ARP_KEY}" "DisplayVersion" "${DISPLAY_VERSION}"
  WriteRegStr HKCU "${ARP_KEY}" "Publisher" "${PUBLISHER}"
  WriteRegStr HKCU "${ARP_KEY}" "DisplayIcon" "$INSTDIR\${APP_EXE}"
  WriteRegStr HKCU "${ARP_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "${ARP_KEY}" "UninstallString" "$\"$INSTDIR\uninstall.exe$\""
  WriteRegStr HKCU "${ARP_KEY}" "QuietUninstallString" "$\"$INSTDIR\uninstall.exe$\" /S"
  WriteRegDWORD HKCU "${ARP_KEY}" "NoModify" 1
  WriteRegDWORD HKCU "${ARP_KEY}" "NoRepair" 1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  IntFmt $0 "0x%08X" $0
  WriteRegDWORD HKCU "${ARP_KEY}" "EstimatedSize" "$0"
  WriteUninstaller "$INSTDIR\uninstall.exe"
SectionEnd

Section "$(SecDesktop)" SEC_DESKTOP
  SetOutPath "$INSTDIR"
  CreateShortCut "$DESKTOP\${APP_NAME}.lnk" "$INSTDIR\${APP_EXE}"
SectionEnd

!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
!insertmacro MUI_DESCRIPTION_TEXT ${SEC_CORE} "$(DescCore)"
!insertmacro MUI_DESCRIPTION_TEXT ${SEC_DESKTOP} "$(DescDesktop)"
!insertmacro MUI_FUNCTION_DESCRIPTION_END

Section "Uninstall"
  SetOutPath "$TEMP"
check_running:
  ClearErrors
  IfFileExists "$INSTDIR\${APP_EXE}" 0 remove_files
  Delete "$INSTDIR\${APP_EXE}"
  IfErrors 0 remove_files
  MessageBox MB_RETRYCANCEL|MB_ICONEXCLAMATION "$(MsgCloseApp)" IDRETRY check_running
  Abort
remove_files:
  ; Only remove files from the verified package manifest. Unknown files and
  ; local model edits stay in place even for silent uninstall and /D paths.
  !include "..\build\installer\uninstall-files.nsh"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"
  Delete "$DESKTOP\${APP_NAME}.lnk"
  Delete "$SMPROGRAMS\${APP_NAME}\${APP_NAME}.lnk"
  RMDir "$SMPROGRAMS\${APP_NAME}"
  DeleteRegKey HKCU "${ARP_KEY}"
  DeleteRegKey /ifempty HKCU "Software\${APP_NAME}"
SectionEnd
